#!/bin/bash

SC_HOME=`dirname $0`
cd $SC_HOME

case $1 in
  guile|gerbil|"")
    if [[ $1 == "" ]]; then
      SCM="guile"
    else
      SCM=$1
    fi
    chmod 755 backends/build
    chmod 755 backends/$SCM/scm
    chmod 755 backends/$SCM/clish.ss
    backends/build $SCM
    gcc src/ownip.c bin/ownip
    ;;
  eth_dev)
    chmod 755 backends/geth_dev/eth
    chmod 755 backends/geth_dev/solc
   #backends/build geth_dev
    if [[ ! -e "chain" ]]; then
      echo "Creating chain"
    else
      echo "chain already exists"
    fi
    if [[ ! -e "a.out" ]]; then
      echo "Creating a.out"
    else
      echo "a.out already exists"
    fi
    ;;
  *)
    echo "build <guile|gerbil|eth_dev> expected"
    ;;
esac
