#!/usr/bin/env bash

SC_HOME=`dirname $0`
cd $SC_HOME

case $1 in
  guile|gerbil|"")
    if [[ $1 == "" ]]; then
      SCM="guile"
    else
      SCM=$1
    fi
    chmod 755 bin/cli
    chmod 755 bin/extip
    mkdir sock
    gcc src/ownip.c -o bin/ownip
    chmod 755 backends/build
    chmod 755 backends/diff
    chmod 755 backends/$SCM/scm
    chmod 755 backends/$SCM/clish.ss
    backends/build $SCM
    backends/build filesocks_unix
    backends/build geth_dev # we are importing eth.ss anyway
    chmod 755 tests/test1.sh
    ;;
  eth_dev)
    chmod 755 backends/geth_dev/eth
    chmod 755 backends/geth_dev/solc
    backends/build geth_dev
    if [[ ! -e "chain" ]]; then
      echo "Creating the chain"
      cp -dpr ./backends/geth_dev/chain .
      cd chain
      geth --datadir "./data" init genesis.json
      cd -
    else
      echo "chain already exists"
    fi
    if [[ ! -e "a.out" ]]; then
      echo "Creating a.out"
      mkdir a.out
      touch a.out/ALIASES
    else
      echo "a.out already exists"
    fi
    ;;
  *)
    echo "build <guile|gerbil|eth_dev> expected"
    ;;
esac
